apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-deploy
  labels:
    app: bank
spec:
  replicas: 10
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
      - name: cont1
        image: xdmahtab/insurance-image:latest
---
apiVersion: v1
kind: Service
metadata:
  name: insurancebankingservice
spec:
  type: LoadBalancer
  selector:
    app: bank
  ports:
    - port: 80
      nodeport: 31433
